#!/bin/bash

source /etc/portage/check-portdir.sh
source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

ebegin "Syncing metadata cache"
egencache --jobs=8 --repo=gentoo --update --update-use-local-desc
eend $?
