#!/bin/bash

source /etc/portage/check-portdir.sh
source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

einfo "updating dtd directory"

cd "${PORTDIR}"/metadata || die "could not cd into '${PORTDIR}/metadata'!"
if [[ -e dtd ]] ; then
	einfo "dtd dir already exists, updating..."
	cd dtd || die "could not cd into 'dtd'!"
	git pull --ff || die "could not pull updates!"
else
	einfo "dtd directory does not exist, cloning..."
	git clone https://anongit.gentoo.org/git/data/dtd.git || die "could not clone repository!"
fi

einfo "done updating dtd directory"
