#!/bin/bash

source /etc/portage/check-portdir.sh
source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

GLSADIR="${PORTDIR}"/metadata/glsa
ebegin "Updating GLSAs"
if [[ -e $GLSADIR ]]; then
	git -C "$GLSADIR" pull --ff
else
	git clone https://anongit.gentoo.org/git/data/glsa.git "$GLSADIR"
fi
eend "$?"
