#!/bin/bash

source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

repository_name="${1}"
repository_path="${3}"

if [[ ${repository_name} == "gentoo" ]]; then
	NEWSDIR="${repository_path}"/metadata/news
	ebegin "Updating news items"
	if [[ -e ${NEWSDIR} ]]; then
		git -C "${NEWSDIR}" pull -q --ff
	else
		git clone -q https://anongit.gentoo.org/git/data/gentoo-news.git "${NEWSDIR}"
	fi
	eend $? "Try to remove ${PORTDIR}/metadata/news"
fi
