#!/bin/bash

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

repository_name="${1}"
repository_path="${3}"

# Number of jobs for egencache, default is number or processors.
parallel_jobs="$(nproc)"

ebegin "Fetching pre-generated metadata cache for ${repository_name}"
rsync -aq rsync://rsync.gentoo.org/gentoo-portage/metadata/md5-cache/ "${repository_path}"/metadata/md5-cache/
eend $?

ebegin "Updating metadata cache for ${repository_name}"
egencache --jobs="${parallel_jobs}" --repo="${repository_name}" --update --update-use-local-desc
eend $?
