#!/bin/bash

source /etc/init.d/functions.sh

repository_name="${1}"
repository_path="${3}"

if [[ ${repository_name} == "gentoo" ]]; then
	DTDDIR="${repository_path}"/metadata/dtd
	ebegin "Updating DTDs"
	if [[ -e ${DTDDIR} ]]; then
		git -C "${DTDDIR}" pull -q --ff
	else
		git clone -q https://anongit.gentoo.org/git/data/dtd.git "${DTDDIR}"
	fi
	eend "$?"
fi
