#!/bin/bash

[[ ${repository_name} == "gentoo" ]] || exit 0

source /lib/gentoo/functions.sh

repository_name="${1}"
repository_path="${3}"

ebegin "Updating herds.xml"
wget -q -O "${repository_path}"/metadata/herds.xml https://api.gentoo.org/packages/herds.xml
eend $?
