#!/bin/bash

source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

repository_name="${1}"
repository_path="${3}"

if [[ ${repository_name} == "gentoo" ]]; then
	ebegin "Updating herds.xml"
	wget -q -O "${repository_path}"/metadata/herds.xml https://api.gentoo.org/packages/herds.xml
	eend $?
fi
