#!/bin/bash

source /etc/init.d/functions.sh
source /etc/portage/util-functions.sh

repository_name="${1}"
repository_path="${3}"

if [[ ${repository_name} == "gentoo" ]]; then
	GLSADIR="${repository_path}"/metadata/glsa
	ebegin "Updating GLSAs"
	if [[ -e ${GLSADIR} ]]; then
		git -C "${GLSADIR}" pull -q --ff
	else
		git clone -q https://anongit.gentoo.org/git/data/glsa.git "${GLSADIR}"
	fi
	eend "$?"
fi
